on: push
name: Reactor done
jobs:
  Build-job:
    name: Build .NET Project
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:7.0
    steps:
      - run: dotnet --version
        name: Check .NET Version
      - uses: actions/checkout@v3
        name: Checkout code
      - run: |
          dotnet publish \
          --configuration Release \
          --output out
        name: Publish .NET Web Application
