on: push
name: Reactor done
jobs:
  Build-job:
    name: Create .NET Project
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - run: dotnet --version
        name: Chech .NET Version